name: Build & Deploy to S3 with Pulumi

on:
  push:
    branches: ['main']
permissions:
  id-token: write
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Install app dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm run lint

      - name: Test Code
        run: pnpm run test
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    environment: AWS-STAGING
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      # Build React App
      - name: Install app dependencies
        run: pnpm install
      - name: Build React app
        run: pnpm run build

      - name: Install Pulumi CLI
        uses: pulumi/actions@v6

      - name: Install infra dependencies
        run: |
          cd infra
          pnpm install

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main # Or a specific version
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # role-to-assume: ${{ vars.AWS_GH_ROLE_ARN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - run: aws sts get-caller-identity

      - name: Preview & Update Pulumi stack
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
        run: |
          aws sts get-caller-identity 
          cd infra
          pulumi up --yes --stack jonpham/static-web-aws-ts/prod

      # - name: Get Bucket Name
      #   id: bucket
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      #   run: |
      #     cd infra
      #     echo "BUCKET_NAME=$(pulumi stack output siteBucketName)" >> $GITHUB_OUTPUT

      # - name: Install app dependencies
      #   run: pnpm install

      # - name: Build React app
      #   run: pnpm run build

      # - name: Upload dist/ to S3
      #   run: |
      #     aws sts get-caller-identity
      #     aws s3 sync dist/ s3://${{ steps.bucket.outputs.BUCKET_NAME }} --delete
