name: Pulumi
on:
  - pull_request
permissions:
  id-token: write
  contents: read
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      - name: Install app dependencies
        run: pnpm install

      - name: Lint Code
        run: pnpm run lint

      - name: Test Code
        run: pnpm run test

  preview:
    name: Preview
    environment: AWS-STAGING
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4

      # Build React App
      - name: Install app dependencies
        run: pnpm install
      - name: Build React app
        run: pnpm run build

      # Prepare AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.AWS_REGION }}
          # role-to-assume: ${{ vars.AWS_GH_ROLE_ARN }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws sts get-caller-identity
      # Deploy infrastructure and upload to S3
      - name: Install infra dependencies
        run: |
          cd infra
          pnpm install
      - uses: pulumi/actions@v6
        with:
          work-dir: infra
          command: up
          stack-name: jonpham/static-web-aws-ts/staging # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      ## PULUMI SYNCED BUCKET DOES THIS FOR PUBLIC S3 Website (STAGING)
      # - name: Get Bucket Name
      #   id: bucket
      #   env:
      #     PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      #   run: |
      #     cd infra
      #     echo "BUCKET_NAME=$(pulumi stack output siteBucketName)" >> $GITHUB_OUTPUT
      # - name: Upload dist/ to S3
      #   run: |
      #     aws sts get-caller-identity
      #     aws s3 sync dist/ s3://${{ steps.bucket.outputs.BUCKET_NAME }} --delete
