name: Pulumi
on:
  - pull_request
jobs:
  preview:
    name: Preview
    environment: AWS-STAGING
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_GH_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: npm install
      - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: static-web-aws-ts # When using an individual account, only use stack-name.
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
